table DimProduct
	lineageTag: 750ffcfd-f145-4602-8b06-d57fa76faabb

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: b14c2215-77a8-4ee5-9be7-3920b00a4c17
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: c50ba508-19a7-4cd9-ad68-88a2e62f44d0
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2dfd7c1f-ce60-43cc-8087-a3d67694fc0d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: eb00266c-bd82-4d2b-a3e9-495bee32608a
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column LaunchYear
		dataType: int64
		formatString: 0
		lineageTag: 3478c4e4-32ee-44bb-a28d-6866ea9f98b1
		summarizeBy: none
		sourceColumn: LaunchYear

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f20b621d-3422-4cc7-9663-8ce9ccd3f9e2
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\dt\DAX\Data\DimProduct.txt"), [Delimiter = ",", Columns = 6, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProductKey", Int64.Type}, {"ProductName", type text}, {"Category", type text}, {"SubCategory", type text}, {"LaunchYear", Int64.Type}, {"Status", type text}})
				in
				  #"Changed column type"

